services:
  utm-track:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: utm-track-app
    restart: always
    ports:
      - "0.0.0.0:3030:3000"
    networks:
      - app_network
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000

networks:
  app_network:
    name: stack_default
    external: true
