services:
  utm-track:
    image: utm-track:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: utm-track
    restart: always
    ports:
      - "0.0.0.0:3030:3000"
    networks:
      - app_network
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000

  meta-cron:
    image: utm-track:local
    container_name: utm-track-meta-cron
    restart: always
    depends_on:
      - utm-track
    networks:
      - app_network
    env_file:
      - .env.production
    command: ["node", "scripts/meta-cron.js"]

networks:
  app_network:
    name: stack_default
    external: true
